
- name: "restart auditd"
  service:
    name: "auditd"
    state: restarted
    enabled: yes
    use: "{% if ansible_os_family == 'RedHat' %}/sbin/service{% else %}auto{% endif %}"
  tags:
    - aspects_auditd

- name: "reload auditd"
  service:
    name: "auditd"
    state: reloaded
    enabled: yes
    use: "{% if ansible_os_family == 'RedHat' %}/sbin/service{% else %}auto{% endif %}"
  tags:
    - aspects_auditd

- name: "start auditd"
  service:
    name: "auditd"
    state: started
    enabled: yes
    use: "{% if ansible_os_family == 'RedHat' %}/sbin/service{% else %}auto{% endif %}"
  tags:
    - aspects_auditd

- name: "stop auditd"
  service:
    name: "auditd"
    state: stopped
    enabled: no
    use: "{% if ansible_os_family == 'RedHat' %}/sbin/service{% else %}auto{% endif %}"
  tags:
    - aspects_auditd